#include <stdio.h>
#include <stdlib.h>
#include <stdint.h>
#include <stdbool.h>
#include <string.h>

#include "args.h"
#include "utils.h"
#include "ascii_art.h"
#include "png_render.h"
#include "tui.h"


static void process_one(
    const char *input_filepath,
    const char *output_filepath, /* may be NULL */
    const char *characters_src,
    int desired_width,
    uint8_t flags,
    bool resize_image,
    const char *font_path
) {
    int width = desired_width, height = 0;
    bool resize = resize_image;

    uint8_t *image = load_image(input_filepath, &width, &height, &resize);

    /* Fresh copy each call so REVERSE_FLAG mutation doesn't compound. */
    char *characters = strdup(characters_src);

    char *output = (flags & GRAYSCALE_FLAG)
        ? get_output_grayscale(image, width, height, characters, flags)
        : get_output_rgb     (image, width, height, characters, flags);

    if ((flags & PNG_FLAG) && output_filepath) {
        char png_path[1024];
        txt_path_to_png(output_filepath, png_path, sizeof png_path);
        int r = render_to_png(png_path, image, width, height,
                              characters_src, flags, font_path, 0,
                              NULL, NULL);
        if (r == 0) {
            fprintf(stderr, "PNG output failed for '%s' (font missing?)\n", png_path);
        } else if (r < 0) {
            fprintf(stderr, "PNG output skipped for '%s' (image too large)\n", png_path);
        }
    }

    if (flags & DEBUG_FLAG) {
        printf(
            "Input: %s \n"
            "Output: %s \n"
            "Resolution: %ix%i \n"
            "Characters (%i): \"%s\" \n",
            input_filepath,
            output_filepath ? output_filepath : "stdout",
            width, height,
            (int)strlen(characters), characters
        );
    }

    if (flags & PRINT_FLAG) {
        printf("%s", output);
    }

    if (output_filepath) {
        FILE *f = fopen(output_filepath, "w");
        if (!f) {
            fprintf(stderr, "Could not create output file '%s'\n", output_filepath);
        } else {
            fputs(output, f);
            fclose(f);
        }
    }

    stbi_image_free(image);
    free(output);
    free(characters);
}

static void write_view_script(const char *out_dir,
                              const char *const *stems, int count)
{
    char script_path[1024];
    snprintf(script_path, sizeof script_path, "%s/view_ascii.ps1", out_dir);
    FILE *f = fopen(script_path, "w");
    if (!f) {
        fprintf(stderr, "Could not create viewer script '%s'\n", script_path);
        return;
    }
    fputs("# Auto-generated by img2ascii. Run with:  powershell -File view_ascii.ps1\n", f);
    fputs("$ErrorActionPreference = 'Stop'\n", f);
    fputs("[Console]::OutputEncoding = [System.Text.Encoding]::UTF8\n", f);
    fputs("$here = Split-Path -Parent $MyInvocation.MyCommand.Path\n", f);
    fputs("$files = @(\n", f);
    for (int i = 0; i < count; i++) {
        fprintf(f, "    \"%s_ascii.txt\"%s\n",
                stems[i], (i + 1 < count) ? "," : "");
    }
    fputs(")\n", f);
    fputs("foreach ($f in $files) {\n", f);
    fputs("    Clear-Host\n", f);
    fputs("    [Console]::Write((Get-Content -Raw -Path (Join-Path $here $f)))\n", f);
    fputs("    Write-Host \"\"\n", f);
    fputs("    Write-Host \"--- $f --- press Enter for next, Ctrl+C to quit ---\"\n", f);
    fputs("    [void](Read-Host)\n", f);
    fputs("}\n", f);
    fclose(f);
}

int main(int argc, char **argv)
{
    /* Launch the TUI when run with no arguments, or with --tui / -t. */
    bool want_tui = (argc == 1);
    for (int i = 1; i < argc && !want_tui; i++) {
        if (strcmp(argv[i], "--tui") == 0 || strcmp(argv[i], "-t") == 0) {
            want_tui = true;
        }
    }
    if (want_tui) {
        run_tui();
        return EXIT_SUCCESS;
    }

    const char *inputs[MAX_INPUTS];
    int input_count = 0;
    char *output_filepath = NULL;
    char *characters = strdup("$@B%8&WM#*oahkbdpqwmZO0QLCJUYXzcvunxrjft/\\|()1{}[]?-_+~<>i!lI;:,\"^`'. ");
    int desired_width = 0;
    uint8_t flags = 0;
    bool resize_image = false;
    const char *font_path = NULL;

    process_arguments(
        argc, argv,
        inputs, &input_count,
        &output_filepath,
        &characters,
        &desired_width,
        &flags,
        &resize_image,
        &font_path
    );

    if ((flags & PNG_FLAG) && font_path == NULL) {
        font_path = find_default_font();
        if (font_path == NULL) {
            fprintf(stderr,
                "Warning: --png set but no font found. "
                "Use --font <FILE> to specify one.\n");
        }
    }

    if (input_count == 1) {
        process_one(inputs[0], output_filepath, characters,
                    desired_width, flags, resize_image, font_path);
        free(characters);
        return EXIT_SUCCESS;
    }

    /* Batch mode. */
    if (output_filepath == NULL) {
        fprintf(stderr, "Batch mode requires -o <DIR>.\n");
        free(characters);
        return EXIT_FAILURE;
    }
    if (!path_is_directory(output_filepath)) {
        fprintf(stderr,
            "Batch output '%s' is not an existing directory.\n", output_filepath);
        free(characters);
        return EXIT_FAILURE;
    }

    /* Suppress per-file console spam unless explicitly requested. */
    uint8_t per_file_flags = flags & ~PRINT_FLAG;

    char  *stem_storage[MAX_INPUTS];
    const char *stems[MAX_INPUTS];
    int    stem_count = 0;

    for (int i = 0; i < input_count; i++) {
        char stem[512];
        path_basename_no_ext(inputs[i], stem, sizeof stem);
        if (!stem[0]) snprintf(stem, sizeof stem, "image_%d", i);

        char out_path[1024];
        snprintf(out_path, sizeof out_path,
                 "%s/%s_ascii.txt", output_filepath, stem);

        printf("[%d/%d] %s -> %s\n", i + 1, input_count, inputs[i], out_path);
        process_one(inputs[i], out_path, characters,
                    desired_width, per_file_flags, resize_image, font_path);

        stem_storage[stem_count] = strdup(stem);
        stems[stem_count] = stem_storage[stem_count];
        stem_count++;
    }

    write_view_script(output_filepath, stems, stem_count);
    printf("Wrote viewer script: %s/view_ascii.ps1\n", output_filepath);

    for (int i = 0; i < stem_count; i++) free(stem_storage[i]);
    free(characters);
    return EXIT_SUCCESS;
}
